language: python

# Use container-based infrastructure
sudo: false

python:
 - pypy
 - pypy3
 - 2.7
 - 3.6
 - 3.5
 - 3.4
 - 3.3
 - 2.6

install:
 - pip install -r requirements.txt
 - pip install coverage
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi

script:
 - coverage run --source=tracery -m nose tests/test_*.py

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pycodestyle pyflakes
 - pyflakes . | tee >(wc -l)
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
