language: python

# Use container-based infrastructure
sudo: false

python:
 - pypy
 - pypy3
 - 2.7
 - 3.6
 - 3.5
 - 3.4

install:
 - pip install -r requirements.txt
 - pip install coverage

script:
 - coverage run --source=tracery -m nose tests/test_*.py

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pyflakes . | tee >(wc -l)
 - pep8 --statistics --count .

matrix:
  fast_finish: true
